"""
performance.py — Self-learning performance tracker.

Design principles
-----------------
* Runs automatically after every closed trade and after every 10 trades
  per strategy (via on_trade_closed).
* NEVER auto-applies suggestions — it only persists them to the DB for
  human review.
* Suggestions are generated by three independent analysers:
    - VIX bucket analysis  (performance by volatility regime)
    - Time-of-day analysis (performance by market session)
    - Day-of-week analysis (performance by weekday)
"""

import logging
import statistics
from collections import defaultdict
from datetime import date, datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple, Union

# ---------------------------------------------------------------------------
# Baseline targets from backtest research
# ---------------------------------------------------------------------------
BACKTEST_BASELINES: dict = {
    "config_d":      {"wr": 0.65, "expectancy": 18.0},
    "credit_spread": {"wr": 0.72, "expectancy": 22.0},
    "five_dte":      {"wr": 0.58, "expectancy": 35.0},
    "earnings":      {"wr": 0.55, "expectancy": 45.0},
    "vpin":          {"wr": 0.60, "expectancy": 12.0},
}

# ---------------------------------------------------------------------------
# Status thresholds (delta = live WR − baseline WR)
# ---------------------------------------------------------------------------
STATUS_THRESHOLDS: dict = {
    "OUTPERFORMING":   +0.05,   # live WR > baseline + 5 ppts
    "IN_LINE":          0.00,   # within ±5 ppts
    "UNDERPERFORMING": -0.10,   # live WR < baseline − 10 ppts
    "DEAD":            -0.20,   # live WR < baseline − 20 ppts, or negative expectancy after 20+ trades
}


class PerformanceTracker:
    """Track, analyse, and surface performance signals for each strategy.

    Parameters
    ----------
    db :
        An initialised ``Database`` instance used for all persistence.
    """

    def __init__(self, db) -> None:
        self.db = db
        self.logger = logging.getLogger("performance")
        self._consecutive_losses: dict = defaultdict(int)
        self._trade_counts: dict = defaultdict(int)

    # ------------------------------------------------------------------
    # Public entry point — called by the trading engine after each close
    # ------------------------------------------------------------------

    def on_trade_closed(self, trade: dict, strategy: str) -> None:
        """Process a newly closed trade.

        * Updates win/loss streak counters.
        * Warns on 3+ consecutive losses.
        * Refreshes the performance summary row in the DB.
        * Triggers full analysis every 10 trades.

        Parameters
        ----------
        trade :
            Dict with at minimum a ``pnl`` key (float).
        strategy :
            Strategy identifier, must match a key in ``BACKTEST_BASELINES``
            or will fall back to a neutral baseline.
        """
        self._trade_counts[strategy] += 1

        if trade.get("pnl", 0.0) > 0:
            self._consecutive_losses[strategy] = 0
        else:
            self._consecutive_losses[strategy] += 1

        streak = self._consecutive_losses[strategy]
        if streak >= 3:
            self.logger.warning(
                "Strategy '%s' is on a %d-trade losing streak. Review conditions.",
                strategy, streak,
            )

        self._update_performance_row(strategy)

        if self._trade_counts[strategy] % 10 == 0:
            self.logger.info(
                "Strategy '%s' — %d trades reached; running pattern analysis.",
                strategy, self._trade_counts[strategy],
            )
            self.run_analysis(strategy)

    # ------------------------------------------------------------------
    # Internal — performance row update
    # ------------------------------------------------------------------

    def _update_performance_row(self, strategy: str) -> None:
        """Recompute aggregate stats and upsert the performance table row."""
        trades = self.db.get_trades_by_strategy(strategy)
        if not trades:
            return

        pnls = [t["pnl"] for t in trades]
        n = len(pnls)
        wins = sum(1 for p in pnls if p > 0)
        losses = n - wins
        wr = wins / n if n > 0 else 0.0
        total_pnl = sum(pnls)

        baseline = BACKTEST_BASELINES.get(strategy, {"wr": 0.5, "expectancy": 0.0})
        vs_backtest_wr = wr - baseline["wr"]
        status = self._compute_status(strategy, wr, total_pnl, n, baseline)

        self.db.insert_performance(
            strategy=strategy,
            date_str=date.today().isoformat(),
            total_trades=n,
            wins=wins,
            losses=losses,
            wr=round(wr, 4),
            total_pnl=round(total_pnl, 2),
            vs_backtest_wr=round(vs_backtest_wr, 4),
            status=status,
        )
        self.logger.debug(
            "Performance updated: strategy=%s n=%d wr=%.2f%% pnl=%.2f status=%s",
            strategy, n, wr * 100, total_pnl, status,
        )

    def _compute_status(
        self,
        strategy: str,
        wr: float,
        total_pnl: float,
        n_trades: int,
        baseline: dict,
    ) -> str:
        """Classify strategy performance relative to its backtest baseline.

        Returns one of:
            INSUFFICIENT_DATA | DEAD | UNDERPERFORMING | IN_LINE | OUTPERFORMING
        """
        if n_trades < 10:
            return "INSUFFICIENT_DATA"

        delta = wr - baseline["wr"]

        # Negative expectancy after 20+ trades is a hard DEAD signal.
        if n_trades >= 20 and (total_pnl / n_trades) < 0:
            return "DEAD"

        if delta < STATUS_THRESHOLDS["DEAD"]:
            return "DEAD"
        if delta < STATUS_THRESHOLDS["UNDERPERFORMING"]:
            return "UNDERPERFORMING"
        if delta >= STATUS_THRESHOLDS["OUTPERFORMING"]:
            return "OUTPERFORMING"
        return "IN_LINE"

    # ------------------------------------------------------------------
    # Pattern analysis — triggered every 10 trades
    # ------------------------------------------------------------------

    def run_analysis(self, strategy: str) -> Optional[str]:
        """Run all pattern analysers against the last 50 trades.

        Any findings are persisted to the DB as pending suggestions.
        The caller is NOT expected to act on them automatically.

        Returns
        -------
        str or None  The first suggestion generated (for logging convenience),
                     or None if no patterns were found.
        """
        trades = self.db.get_trades_by_strategy(strategy)
        if len(trades) < 10:
            self.logger.info(
                "run_analysis: not enough trades for '%s' (%d < 10).", strategy, len(trades)
            )
            return None

        # Use the most recent 50 trades for the analysis window.
        window = trades[:50]

        suggestions = []

        for analyser in (
            self._analyze_vix_buckets,
            self._analyze_time_of_day,
            self._analyze_day_of_week,
        ):
            result = analyser(window)
            if result:
                suggestions.append(result)

        for suggestion_text in suggestions:
            self.db.insert_suggestion(strategy, suggestion_text)
            self.logger.info(
                "New suggestion for '%s': %s", strategy, suggestion_text
            )

        return suggestions[0] if suggestions else None

    # ------------------------------------------------------------------
    # Individual analysers
    # ------------------------------------------------------------------

    def _analyze_vix_buckets(self, trades: list) -> Optional[str]:
        """Find VIX regimes where performance significantly diverges from average.

        Buckets: VIX <15 | 15–18 | 18–22 | >22

        Returns a suggestion string if a meaningful pattern is detected,
        otherwise None.
        """
        buckets: dict = {"<15": [], "15-18": [], "18-22": [], ">22": []}

        for t in trades:
            vix = t.get("vix")
            if vix is None:
                continue
            try:
                vix = float(vix)
            except (TypeError, ValueError):
                continue

            pnl = t.get("pnl", 0.0)
            if vix < 15:
                buckets["<15"].append(pnl)
            elif vix < 18:
                buckets["15-18"].append(pnl)
            elif vix < 22:
                buckets["18-22"].append(pnl)
            else:
                buckets[">22"].append(pnl)

        all_pnls = [t.get("pnl", 0.0) for t in trades]
        n_total = len(all_pnls)
        if n_total == 0:
            return None
        overall_wr = sum(1 for p in all_pnls if p > 0) / n_total

        best_bucket = best_wr = None
        worst_bucket = worst_wr = None

        for label, pnls in buckets.items():
            if len(pnls) < 5:
                continue
            wr = sum(1 for p in pnls if p > 0) / len(pnls)
            if best_wr is None or wr > best_wr:
                best_wr = wr
                best_bucket = label
            if worst_wr is None or wr < worst_wr:
                worst_wr = wr
                worst_bucket = label

        if best_wr is not None and best_wr > overall_wr + 0.15:
            return (
                f"VIX EDGE: Win rate is {best_wr:.0%} in VIX bucket {best_bucket} "
                f"vs overall {overall_wr:.0%}. "
                f"Consider restricting entries to this volatility regime."
            )

        if worst_wr is not None and worst_wr < overall_wr - 0.20:
            return (
                f"VIX DRAG: Win rate drops to {worst_wr:.0%} in VIX bucket {worst_bucket} "
                f"vs overall {overall_wr:.0%}. "
                f"Consider avoiding entries when VIX is in this range."
            )

        return None

    def _analyze_time_of_day(self, trades: list) -> Optional[str]:
        """Find intraday time windows where performance significantly diverges.

        Buckets: 9–10 | 10–11 | 11–12 | 12–14 | 14–16

        Returns a suggestion string or None.
        """
        bucket_map: dict = {
            "09-10": (9, 10),
            "10-11": (10, 11),
            "11-12": (11, 12),
            "12-14": (12, 14),
            "14-16": (14, 16),
        }
        buckets: dict = {label: [] for label in bucket_map}

        for t in trades:
            ts = t.get("timestamp", "")
            try:
                hour = datetime.fromisoformat(ts).hour
            except (ValueError, TypeError):
                continue

            pnl = t.get("pnl", 0.0)
            for label, (start, end) in bucket_map.items():
                if start <= hour < end:
                    buckets[label].append(pnl)
                    break

        all_pnls = [t.get("pnl", 0.0) for t in trades]
        n_total = len(all_pnls)
        if n_total == 0:
            return None
        overall_wr = sum(1 for p in all_pnls if p > 0) / n_total

        best_label = best_wr = None
        for label, pnls in buckets.items():
            if len(pnls) < 5:
                continue
            wr = sum(1 for p in pnls if p > 0) / len(pnls)
            if best_wr is None or wr > best_wr:
                best_wr = wr
                best_label = label

        if best_wr is not None and best_wr > overall_wr + 0.15:
            return (
                f"TIME EDGE: Win rate is {best_wr:.0%} during {best_label} ET "
                f"vs overall {overall_wr:.0%}. "
                f"Consider concentrating entry signals in this window."
            )

        return None

    def _analyze_day_of_week(self, trades: list) -> Optional[str]:
        """Find weekdays where performance significantly diverges from average.

        Returns a suggestion string or None.
        """
        day_names = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
        buckets: dict = {name: [] for name in day_names}

        for t in trades:
            ts = t.get("timestamp", "")
            try:
                weekday = datetime.fromisoformat(ts).weekday()  # 0 = Monday
                if 0 <= weekday <= 4:
                    buckets[day_names[weekday]].append(t.get("pnl", 0.0))
            except (ValueError, TypeError):
                continue

        all_pnls = [t.get("pnl", 0.0) for t in trades]
        n_total = len(all_pnls)
        if n_total == 0:
            return None
        overall_wr = sum(1 for p in all_pnls if p > 0) / n_total

        best_day = best_wr = None
        for day, pnls in buckets.items():
            if len(pnls) < 3:
                continue
            wr = sum(1 for p in pnls if p > 0) / len(pnls)
            if best_wr is None or wr > best_wr:
                best_wr = wr
                best_day = day

        if best_wr is not None and best_wr > overall_wr + 0.20:
            return (
                f"DAY-OF-WEEK EDGE: Win rate is {best_wr:.0%} on {best_day}s "
                f"vs overall {overall_wr:.0%}. "
                f"Consider prioritising entries on {best_day}."
            )

        return None

    # ------------------------------------------------------------------
    # Status query
    # ------------------------------------------------------------------

    def get_strategy_status(self, strategy: str) -> str:
        """Return the most recent status label for *strategy* from the DB.

        Returns 'INSUFFICIENT_DATA' when no performance row exists yet.
        """
        history = self.db.get_performance_history(days=365)
        # get_performance_history returns rows newest-first per our DB query.
        for row in history:
            if row.get("strategy") == strategy:
                return row.get("status", "INSUFFICIENT_DATA")
        return "INSUFFICIENT_DATA"
